apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      name: example
    spec:
      containers:
      - name: example-container
        image: registry-service:5000/hello-world
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
